--------------------------------------------------------
--  Fichier créé - samedi-avril-23-2022   
--------------------------------------------------------
DROP TABLE "SYSTEM"."EMPLOYES";
DROP TABLE "SYSTEM"."DEMANDE_CONGEE";
DROP TABLE "SYSTEM"."LOGIN";
DROP TABLE "SYSTEM"."CONGEE";
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."EMPLOYES" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOMPRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PROFESSION" VARCHAR2(20 BYTE), 
	"ASSURANCE" VARCHAR2(20 BYTE), 
	"DATE_ENTREE" DATE, 
	"NAISSANCE" DATE, 
	"NOMBRE_ENFANTS" NUMBER, 
	"CNSS" NUMBER, 
	"SALAIRE" NUMBER, 
	"NATIONNALITE" VARCHAR2(20 BYTE), 
	"NUM_TELE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEMANDE_CONGEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DEMANDE_CONGEE" 
   (	"NATURE_CONGES" VARCHAR2(20 BYTE), 
	"NOM_EMPLOYES" VARCHAR2(20 BYTE), 
	"NUM_TELE_EMPLOYES" VARCHAR2(20 BYTE), 
	"DATE_DEPART_CONGE" DATE, 
	"DATE_RETOUR_CONGE" DATE, 
	"CIN_EMPLOYE" VARCHAR2(20 BYTE), 
	"FONCTION_EMPLOYE" VARCHAR2(20 BYTE), 
	"DATE_DEMANDE" DATE, 
	"IDC" NUMBER, 
	"REPONSE" VARCHAR2(20 BYTE), 
	"CAUSE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."LOGIN" 
   (	"LOGIN_P" VARCHAR2(20 BYTE), 
	"NOM_ET_PRENOM" VARCHAR2(20 BYTE), 
	"TYPE_UTILISATEUR" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONGEE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."CONGEE" 
   (	"ID_CONGEE" NUMBER, 
	"ETAT_CONGEE" VARCHAR2(20 BYTE), 
	"DUREE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.EMPLOYES
SET DEFINE OFF;
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('11111111','chaima','chaima','Tunis','ingenieur','comar',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'1','1122','120','Tunisienne','21318555');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('22222222','Farah','farah@esprit.tn','Tunis','ingenieure','baraka',to_date('03/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'2','1122','1200','Tunisienne','25015214');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('11133333','TEST','TEST','ttt','ee','AA',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'3','1122','50','francaise','1112222222');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('33344444','OMAR','Omar@esprit.tn','RUE DE SAHEL','INGENIEUR','TIJENI',to_date('03/01/00','DD/MM/RR'),to_date('04/01/00','DD/MM/RR'),'2','123','80','Tunisienne','22939765');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('2389','PPPPP','PPPPPP','Tunis','ingenieur','comar',to_date('03/01/00','DD/MM/RR'),to_date('27/06/00','DD/MM/RR'),'1','1122','1200','Tunisienne','88893');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('22244444','cheima','Cheima','Tunis','Ingenieure','COMAR',to_date('04/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'1','1234','50','Tunisienne','213188899');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('17777777','testtt','testtt','tiunis','ingenieure','ggg',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'3','1188','50','Tunisienne','1234567');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('1234567','saloua','saloua','Tunis','prof','AAA',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'1','1234','1200','Tunisienne','221111');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('11112277','sahar','chaaa','sidi elbachir','etyudiante','234',to_date('04/01/00','DD/MM/RR'),to_date('04/01/00','DD/MM/RR'),'3','1234','50','Tunisienne','2137777');
Insert into SYSTEM.EMPLOYES (CIN,NOMPRENOM,EMAIL,ADRESSE,PROFESSION,ASSURANCE,DATE_ENTREE,NAISSANCE,NOMBRE_ENFANTS,CNSS,SALAIRE,NATIONNALITE,NUM_TELE) values ('12000000','chaimouma','NINI','hello','llmmnini','ZZZ',to_date('03/01/00','DD/MM/RR'),to_date('02/01/00','DD/MM/RR'),'2','111','1200','Tunisienne','2133333');
REM INSERTING into SYSTEM.DEMANDE_CONGEE
SET DEFINE OFF;
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maladie','PPPPP','88893',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'2389','ingenieur',to_date('01/01/00','DD/MM/RR'),null,'en attente','malade');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maladie','TEST','1112222222',to_date('03/01/00','DD/MM/RR'),to_date('03/01/00','DD/MM/RR'),'11133333','ee',to_date('01/01/00','DD/MM/RR'),null,'refuser','malade');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('paid leave','OMAR','22939765',to_date('02/01/00','DD/MM/RR'),to_date('08/01/00','DD/MM/RR'),'33344444','INGENIEUR',to_date('02/01/00','DD/MM/RR'),null,'accepter','maldie chronique');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maladie','chaimouma','2133333',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'12000000','llmmnini',to_date('01/01/00','DD/MM/RR'),null,'accepter','malaaaaade');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maternit??','saloua','221111',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'1234567','prof',to_date('01/01/00','DD/MM/RR'),null,'refuser','HELLO');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maternit??','Farah','25015214',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'22222222','ingenieure',to_date('01/01/00','DD/MM/RR'),null,'refuser','KKK');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maternit??','sahar','2137777',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'11112277','etyudiante',to_date('01/01/00','DD/MM/RR'),null,'en attente','hhhhh');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maternit??','testtt','1234567',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'17777777','ingenieure',to_date('01/01/00','DD/MM/RR'),null,'en attente','jjjj');
Insert into SYSTEM.DEMANDE_CONGEE (NATURE_CONGES,NOM_EMPLOYES,NUM_TELE_EMPLOYES,DATE_DEPART_CONGE,DATE_RETOUR_CONGE,CIN_EMPLOYE,FONCTION_EMPLOYE,DATE_DEMANDE,IDC,REPONSE,CAUSE) values ('Maternit??','cheima','213188899',to_date('01/01/00','DD/MM/RR'),to_date('01/01/00','DD/MM/RR'),'22244444','Ingenieure',to_date('01/01/00','DD/MM/RR'),null,'en attente','hhhh');
REM INSERTING into SYSTEM.LOGIN
SET DEFINE OFF;
REM INSERTING into SYSTEM.CONGEE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."EMPLOYES_PK" ON "SYSTEM"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_EMAIL" ON "SYSTEM"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UK_EMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UK_EMP" ON "SYSTEM"."EMPLOYES" ("NOMPRENOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMP
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."PK_EMP" ON "SYSTEM"."DEMANDE_CONGEE" ("CIN_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMPTEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMPTEE_PK" ON "SYSTEM"."LOGIN" ("LOGIN_P") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CONGEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."CONGEE_PK" ON "SYSTEM"."CONGEE" ("ID_CONGEE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("NOMPRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("EMAIL" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("ADRESSE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("PROFESSION" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("ASSURANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("DATE_ENTREE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("NAISSANCE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("NOMBRE_ENFANTS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("CNSS" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("NATIONNALITE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" MODIFY ("NUM_TELE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "UK_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."EMPLOYES" ADD CONSTRAINT "UK_EMP" UNIQUE ("NOMPRENOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEMANDE_CONGEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("CIN_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("NATURE_CONGES" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("NOM_EMPLOYES" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("NUM_TELE_EMPLOYES" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("DATE_DEPART_CONGE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("DATE_RETOUR_CONGE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("CIN_EMPLOYE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("FONCTION_EMPLOYE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("DATE_DEMANDE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("REPONSE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" MODIFY ("CAUSE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGIN" ADD CONSTRAINT "COMPTEE_PK" PRIMARY KEY ("LOGIN_P")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."LOGIN" MODIFY ("LOGIN_P" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LOGIN" MODIFY ("NOM_ET_PRENOM" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."LOGIN" MODIFY ("TYPE_UTILISATEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONGEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."CONGEE" ADD CONSTRAINT "CONGEE_PK" PRIMARY KEY ("ID_CONGEE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "SYSTEM"."CONGEE" MODIFY ("ID_CONGEE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CONGEE" MODIFY ("ETAT_CONGEE" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."CONGEE" MODIFY ("DUREE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEMANDE_CONGEE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" ADD CONSTRAINT "FK_CONGE" FOREIGN KEY ("IDC")
	  REFERENCES "SYSTEM"."CONGEE" ("ID_CONGEE") ENABLE;
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" ADD CONSTRAINT "FK_EMP" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "SYSTEM"."EMPLOYES" ("CIN") ENABLE;
 
  ALTER TABLE "SYSTEM"."DEMANDE_CONGEE" ADD CONSTRAINT "FK_NOM_EMP" FOREIGN KEY ("NOM_EMPLOYES")
	  REFERENCES "SYSTEM"."EMPLOYES" ("NOMPRENOM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."LOGIN" ADD CONSTRAINT "FK_EMP_CIN" FOREIGN KEY ("LOGIN_P")
	  REFERENCES "SYSTEM"."EMPLOYES" ("CIN") ENABLE;
