--------------------------------------------------------
--  File created - Monday-April-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "ASH"."EMPLOYES" 
   (	"CIN" NUMBER(*,0), 
	"NOMPRENOM" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"PROFESSION" VARCHAR2(20 BYTE), 
	"ASSURANCE" VARCHAR2(20 BYTE), 
	"DATE_ENTREE" DATE, 
	"NAISSANCE" DATE, 
	"NOMBRE_ENFANTS" NUMBER, 
	"CNSS" NUMBER, 
	"SALAIRE" NUMBER, 
	"NATIONNALITE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURE
--------------------------------------------------------

  CREATE TABLE "ASH"."FACTURE" 
   (	"NUMFA" NUMBER, 
	"DATE_FACTURE" VARCHAR2(40 BYTE), 
	"TYPE_FACTURE" VARCHAR2(40 BYTE), 
	"TVA" VARCHAR2(20 BYTE), 
	"DESCREPTION" VARCHAR2(400 BYTE), 
	"EMAIL" VARCHAR2(80 BYTE), 
	"MONTANT" FLOAT(126), 
	"TELEPHONE" NUMBER, 
	"TOTAL" FLOAT(126), 
	"TRANSPORT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "ASH"."FOURNISSEUR" 
   (	"NUMF" NUMBER, 
	"NOMF" VARCHAR2(20 BYTE), 
	"PRENF" VARCHAR2(20 BYTE), 
	"ADDF" VARCHAR2(20 BYTE), 
	"TELF" NUMBER, 
	"TYPEF" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PAIEMENT
--------------------------------------------------------

  CREATE TABLE "ASH"."PAIEMENT" 
   (	"IDPAIEMENT" NUMBER(5,0), 
	"NUMFA" NUMBER(5,0), 
	"DATE_PAIEMENT" VARCHAR2(50 BYTE), 
	"TOTAL" VARCHAR2(20 BYTE), 
	"PAYMENT_VALIDATION" VARCHAR2(20 BYTE), 
	"NUMF" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJETS
--------------------------------------------------------

  CREATE TABLE "ASH"."PROJETS" 
   (	"ID" NUMBER, 
	"NOMPROJET" VARCHAR2(4000 BYTE), 
	"LOCALISATION" VARCHAR2(4000 BYTE), 
	"DATEDABUT" DATE, 
	"DATEFIN" DATE, 
	"SURFACE" NUMBER, 
	"CHEFPROJET" VARCHAR2(20 BYTE), 
	"COUT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ASH.EMPLOYES
SET DEFINE OFF;
REM INSERTING into ASH.FACTURE
SET DEFINE OFF;
Insert into ASH.FACTURE (NUMFA,DATE_FACTURE,TYPE_FACTURE,TVA,DESCREPTION,EMAIL,MONTANT,TELEPHONE,TOTAL,TRANSPORT) values (236666,'1/1/2000','Actif','20%','bfdbdbd','Achref.ealrbi@gmail.com',1022,12222222,1122,'TRUCK');
Insert into ASH.FACTURE (NUMFA,DATE_FACTURE,TYPE_FACTURE,TVA,DESCREPTION,EMAIL,MONTANT,TELEPHONE,TOTAL,TRANSPORT) values (123666,'1/1/2000','Actif','20%','dfdffdfdfgdfs','Achref.ealrbi@gmail.com',12366,12369999,12466,'TRUCK');
Insert into ASH.FACTURE (NUMFA,DATE_FACTURE,TYPE_FACTURE,TVA,DESCREPTION,EMAIL,MONTANT,TELEPHONE,TOTAL,TRANSPORT) values (665,'1/1/2000','Pasif','20%','ghxghgx','Achref.ealrbi@gmail.com',64456,45555555,64556,'TRUCK');
Insert into ASH.FACTURE (NUMFA,DATE_FACTURE,TYPE_FACTURE,TVA,DESCREPTION,EMAIL,MONTANT,TELEPHONE,TOTAL,TRANSPORT) values (6652,'1/1/2000','Pasif','20%','ghxghgx','Achref.ealrbi@gmail.com',64456,45555555,64556,'TRUCK');
Insert into ASH.FACTURE (NUMFA,DATE_FACTURE,TYPE_FACTURE,TVA,DESCREPTION,EMAIL,MONTANT,TELEPHONE,TOTAL,TRANSPORT) values (1515,'1/1/2000','Actif','20%','dsfdsdfd','Achref.ealrbi@gmail.com',151,51151655,251,'TRUCK');
REM INSERTING into ASH.FOURNISSEUR
SET DEFINE OFF;
Insert into ASH.FOURNISSEUR (NUMF,NOMF,PRENF,ADDF,TELF,TYPEF) values (7777,'Ash','Elarbi','5Ruenewyork',27855555,'Cloisons et briques');
Insert into ASH.FOURNISSEUR (NUMF,NOMF,PRENF,ADDF,TELF,TYPEF) values (2569,'Ff','Sada','sadsad',51515115,'yajour');
REM INSERTING into ASH.PAIEMENT
SET DEFINE OFF;
Insert into ASH.PAIEMENT (IDPAIEMENT,NUMFA,DATE_PAIEMENT,TOTAL,PAYMENT_VALIDATION,NUMF) values (14599,1569,'Mon Apr 4 2022','10000','Not Yet',2569);
Insert into ASH.PAIEMENT (IDPAIEMENT,NUMFA,DATE_PAIEMENT,TOTAL,PAYMENT_VALIDATION,NUMF) values (1459,1569,'Mon Apr 4 2022','6000','Verified',2569);
Insert into ASH.PAIEMENT (IDPAIEMENT,NUMFA,DATE_PAIEMENT,TOTAL,PAYMENT_VALIDATION,NUMF) values (777,9559,'Mon Apr 4 2022','25000','Verified',7777);
Insert into ASH.PAIEMENT (IDPAIEMENT,NUMFA,DATE_PAIEMENT,TOTAL,PAYMENT_VALIDATION,NUMF) values (771,6589,'Mon Apr 4 2022','7350','Not Yet',7777);
REM INSERTING into ASH.PROJETS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index FACTURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASH"."FACTURE_PK" ON "ASH"."FACTURE" ("NUMFA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASH"."FOURNISSEUR_PK" ON "ASH"."FOURNISSEUR" ("NUMF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASH"."UNIQUE_EMAIL" ON "ASH"."EMPLOYES" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_NOM
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASH"."UNIQUE_NOM" ON "ASH"."EMPLOYES" ("NOMPRENOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDPAIEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ASH"."IDPAIEMENT_PK" ON "ASH"."PAIEMENT" ("IDPAIEMENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "ASH"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
 
  ALTER TABLE "ASH"."EMPLOYES" ADD PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."EMPLOYES" ADD CONSTRAINT "UNIQUE_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."EMPLOYES" ADD CONSTRAINT "UNIQUE_NOM" UNIQUE ("NOMPRENOM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "ASH"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("NUMF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."FOURNISSEUR" MODIFY ("NUMF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURE
--------------------------------------------------------

  ALTER TABLE "ASH"."FACTURE" ADD CONSTRAINT "FACTURE_PK" PRIMARY KEY ("NUMFA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."FACTURE" MODIFY ("NUMFA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJETS
--------------------------------------------------------

  ALTER TABLE "ASH"."PROJETS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "ASH"."PROJETS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."PROJETS" ADD UNIQUE ("NOMPROJET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."PROJETS" ADD UNIQUE ("LOCALISATION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAIEMENT
--------------------------------------------------------

  ALTER TABLE "ASH"."PAIEMENT" ADD CONSTRAINT "IDPAIEMENT_PK" PRIMARY KEY ("IDPAIEMENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "ASH"."PAIEMENT" MODIFY ("IDPAIEMENT" NOT NULL ENABLE);
